[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmds = [
  "pip install -r assetflow_backend/requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "cd assetflow_backend && gunicorn as