[build]
  command = "npm run build -- --configuration production"
  publish = "dist/assetflow-frontend/browser"
  base = "assetflow-frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200