[build]
  command = "npm run build -- --base-href=/" # <-- Â¡AÃ±adir este flag!
  publish = "dist/assetflow-frontend"
  base = "assetflow-frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200